# Generated by Django 2.0.7 on 2018-07-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20180726_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-updated_date',)},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='published_in',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='examform',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
