# Generated by Django 2.0.7 on 2018-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='http://placehold.it/100x100', upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
