# Generated by Django 2.0.7 on 2018-07-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategories',
            options={'ordering': ('title',), 'verbose_name': 'Faq Category', 'verbose_name_plural': 'Faq Categories'},
        ),
    ]
