# Generated by Django 2.0.7 on 2018-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(upload_to='uploads', verbose_name='Upload File'),
        ),
    ]
